# 기본 빌드 설정 (사용되지 않음)
[build]
  publish = "."
  command = "echo 'No default build'"

# Admin 프로젝트 배포 설정
[context.admin]
  command = "cd Admin && yarn install && yarn build"
  publish = "Admin/dist"
  environment = { NODE_VERSION = "20" }

# Web 프로젝트 배포 설정  
[context.web]
  command = "cd Web && yarn install && yarn build"
  publish = "Web/dist"
  environment = { NODE_VERSION = "20" }

# 리다이렉트 설정 - SPA 라우팅
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# 헤더 설정
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Content-Type = "font/woff2"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Content-Type = "font/woff"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Content-Type = "font/ttf"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.otf"
  [headers.values]
    Content-Type = "font/otf"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "public, max-age=31536000, immutable"

# HTML 파일에 대한 헤더 설정
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html"
    X-Content-Type-Options = "nosniff"
    Cache-Control = "no-cache, no-store, must-revalidate"