[build]
  publish = "dist"
  command = "yarn build"
  environment = { NODE_VERSION = "20" }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ 루트 경로는 적절한 캐시 허용
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=300"

# ✅ index.html은 적절한 캐시 허용
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=300"

# ✅ HTML 파일은 적절한 캐시 허용
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, must-revalidate, max-age=300"

# ✅ 해시 달린 정적 에셋은 강캐시
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# 보안 헤더
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
